name: gds

on:
  workflow_dispatch:
  push:
    # Don't run on project submissions:
    branches-ignore:
      - projects/tt_um_*
  pull_request:
    # Don't run on project submissions:
    paths-ignore:
      - projects/tt_um_*/**

jobs:
  gds:
    env:
      OPENLANE_TAG: 2.0.0a53
      SKY130_PDK_VERSION: 12df12e2e74145e31c5a13de02f9a1e176b56e67
      PYTHONIOENCODING: utf-8
      PDK_ROOT: /home/runner/pdk

    # ubuntu
    runs-on: ubuntu-latest
    steps:
      # need the repo checked out
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Checkout OpenLane 2 repo
        uses: actions/checkout@v3
        with:
          repository: efabless/openlane2
          path: openlane2
          ref: ${{ env.OPENLANE_TAG }}

      - name: Patch OpenLane 2
        working-directory: openlane2
        run: |
          git apply ../patches/openlane2.patch

      # Set Python up
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r tt-multiplexer/py/requirements.txt -r tt/requirements.txt

      # Install yosys (required for tt/configure.py)
      - name: install oss-cad-suite
        uses: YosysHQ/setup-oss-cad-suite@v2
        with:
          version: '2023-05-27'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update caravel configuration
        run: python ./tt/configure.py --update-caravel

      - uses: cachix/install-nix-action@v20

      - uses: cachix/cachix-action@v12
        with:
          name: openlane
          extraPullNames: openlane

      - name: Install Sky130 PDK
        uses: TinyTapeout/volare-action@v1
        with:
          pdk_name: sky130
          pdk_version: ${{ env.SKY130_PDK_VERSION }}
          pdk_root: ${{ env.PDK_ROOT }}

      #    - name: uncompress gds files
      #      run: gunzip -v gds/*.gds.gz

      # run OpenLane to build the GDS
      - name: Harden tt_ctrl
        working-directory: tt-multiplexer/ol2/tt_ctrl
        run: nix-shell $GITHUB_WORKSPACE/openlane2/shell.nix --run "python build.py"

      - name: Harden tt_mux
        working-directory: tt-multiplexer/ol2/tt_mux
        run: nix-shell $GITHUB_WORKSPACE/openlane2/shell.nix --run "python build.py"

      - name: Copy macros
        run: python ./tt/configure.py --copy-macros

      - name: Harden tt_top
        working-directory: tt-multiplexer/ol2/tt_top
        run: nix-shell $GITHUB_WORKSPACE/openlane2/shell.nix --run "python build.py --skip-xor-checks"

      - name: Copy final results
        run: python ./tt/configure.py --copy-final-results

      - name: Create eFabless submission
        run: python ./tt/configure.py --create-efabless-submission

      - name: upload GDS artifact
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: GDS
          path: tt-multiplexer/ol2/tt_top/runs/RUN_*/*

      - name: upload macros artifact
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: macros
          path: |
            gds/*
            lef/*
            spef/*
            verilog/gl/*

      - name: upload shuttle_index.json
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: shuttle_index
          path: shuttle_index.json

      - name: upload Efabless submission directory
        uses: actions/upload-artifact@v3
        with:
          name: efabless_submission
          path: efabless
