name: mpw_precheck

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["gds"]
    types: [completed]

jobs:
  mpw_precheck:
    env:
      PYTHONIOENCODING: utf-8
      PDK_ROOT: /home/runner/pdk

    # ubuntu
    runs-on: ubuntu-latest
    steps:
      # need the repo checked out
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Load OpenLane environment variables
        run: cat .github/config/openlane.txt | tee -a $GITHUB_ENV

      - name: Checkout Precheck Repo
        uses: actions/checkout@v4
        with:
          repository: efabless/mpw_precheck
          path: mpw_precheck

      - name: Install Sky130 PDK
        uses: TinyTapeout/volare-action@v2
        with:
          pdk_name: sky130
          pdk_version: ${{ env.SKY130_PDK_VERSION }}
          pdk_root: ${{ env.PDK_ROOT }}

      - name: Download artifact (run id = ${{ github.event.workflow_run.id }})
        uses: dawidd6/action-download-artifact@v3
        id: download_artifact
        with:
          workflow: gds.yaml
          run_id: ${{ github.event.workflow_run.id }}
          workflow_conclusion: success
          name: efabless_submission
          path: tinytapeout-submission

      - name: Run precheck (run id = ${{ fromJSON(steps.download_artifact.outputs.artifacts)[0].workflow_run.id }})
        working-directory: mpw_precheck
        run: |
          docker run -v $(pwd):/opt/mpw_precheck \
            -v "$INPUT_DIRECTORY":"$INPUT_DIRECTORY" -v "$PDK_PATH":"$PDK_PATH" \
            -e INPUT_DIRECTORY="$INPUT_DIRECTORY" -e PDK_PATH="$PDK_PATH" -e PDK_ROOT="$PDK_ROOT" \
            -u $(id -u "$USER"):$(id -g "$USER") \
            -w /opt/mpw_precheck \
            efabless/mpw_precheck:latest ./run_precheck.sh $CHECKS
        env:
          CHECKS: |
            default
            consistency
            gpio_defines
            xor
            klayout_feol
            klayout_beol
            klayout_offgrid
            klayout_met_min_ca_density
            klayout_pin_label_purposes_overlapping_drawing
            klayout_zeroarea
            oeb
            illegal_cellname_check
          # Skipped checks: magic_drc (it's very slow)
          PDK_PATH: ${{ env.PDK_ROOT }}/sky130A
          INPUT_DIRECTORY: ${{ github.workspace }}/tinytapeout-submission

      - name: Upload precheck results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: precheck_results
          path: tinytapeout-submission/precheck_results
