name: verification

on:
  workflow_dispatch:
  push:
    # Don't run on project submissions:
    branches-ignore:
      - projects/tt_um_*
  pull_request:
    # Don't run on project submissions:
    paths-ignore:
      - projects/tt_um_*/**

jobs:
  verification:
    env:
      SKY130_PDK_VERSION: 1341f54f5ce0c4955326297f235e4ace1eb6d419
      PDK_ROOT: /home/runner/pdk
      MPW_TAG: mpw-9a

    # ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Clone caravel
        uses: actions/checkout@v3
        with:
          repository: efabless/caravel-lite
          ref: ${{ env.MPW_TAG }}
          path: caravel

      - name: Install sky130A PDK
        uses: TinyTapeOut/volare-action@v1
        with:
          pdk_version: ${{ env.SKY130_PDK_VERSION }}
          pdk_root: ${{ env.PDK_ROOT }}

      - name: Install management core wrapper
        working-directory: caravel
        run: make install_mcw

      - name: Install RISC-V GCC
        run: |
          wget https://static.dev.sifive.com/dev-tools/riscv64-unknown-elf-gcc-8.3.0-2020.04.1-x86_64-linux-ubuntu14.tar.gz
          tar -xzf riscv64-unknown-elf-gcc-8.3.0-2020.04.1-x86_64-linux-ubuntu14.tar.gz

      # Set Python up
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r tt/requirements.txt -r tt-multiplexer/py/requirements.txt -r verilog/dv/mux_ext/requirements.txt

      - name: install iverilog
        run: sudo apt-get update && sudo apt-get install -y iverilog

      - name: Configure the multiplexer for testing
        run: python ./tt/configure.py --update-shuttle --test

      # run first set of tests
      - name: Mux simulation (without caravel)
        working-directory: verilog/dv/mux
        run: make clean test_mux

      - name: Mux + caravel simulation
        working-directory: verilog/dv/mux_ext
        run: make clean coco_test
        env:
          DESIGNS: ${{ github.workspace }}
          TARGET_PATH: ${{ github.workspace }}
          MGMT_AREA_ROOT: ${{ github.workspace }}/caravel/mgmt_core_wrapper
          MCW_ROOT: ${{ github.workspace }}/caravel/mgmt_core_wrapper
          CARAVEL_ROOT: ${{ github.workspace }}/caravel
          CORE_VERILOG_PATH: ${{ github.workspace }}/caravel/mgmt_core_wrapper/verilog
          GCC_PATH: ${{ github.workspace }}/riscv64-unknown-elf-gcc-8.3.0-2020.04.1-x86_64-linux-ubuntu14/bin/
          GCC_PREFIX: riscv64-unknown-elf
